# Assignment Chapter 2 - MACHINE LEARNING [Case #1]
Startup Campus, Indonesia - `Artificial Intelligence (AI)` (Batch 7)
* Dataset: SC_HW1_bank_data
* Libraries: Pandas, Numpy, Scikit-learn
* Objective: Classification with Supervised Machine Learning Models

`PERSYARATAN` Semua modul (termasuk versi yang sesuai) sudah di-install dengan benar.
<br>`CARA PENGERJAAN` Lengkapi baris kode yang ditandai dengan **#TODO**.
<br>`TARGET PORTFOLIO` Peserta mampu membandingkan akurasi klasifikasi dari berbagai model *supervised learning*.

### Import Library

In [ ]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split as tts
from sklearn.model_selection import GridSearchCV

from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

### Read Dataset

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/Rietaros/kampus_merdeka/main/SC_HW1_bank_data.csv')
df.columns

Index(['RowNumber', 'CustomerId', 'Geography', 'Gender', 'Age', 'Tenure',
       'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember',
       'EstimatedSalary', 'Exited'],
      dtype='object')

In [ ]:
# TODO: Hilangkan kolom yang tidak relevan untuk pemodelan
# Memilih kolom yang relevan
df = df[['Geography', 'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts',
         'HasCrCard', 'IsActiveMember', 'EstimatedSalary', 'Exited']].copy()

# Melihat data yang sudah difilter
df.head()


Geography  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0    France  Female   42       2       0.00              1          1   
1     Spain  Female   41       1   83807.86              1          0   
2    France  Female   42       8  159660.80              3          1   
3    France  Female   39       1       0.00              2          0   
4     Spain  Female   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  
0               1        101348.88       1  
1               1        112542.58       0  
2               0        113931.57       1  
3               0         93826.63       0  
4               1         79084.10       0

### Preprocessing

In [ ]:
# TODO: Lakukan One-Hot Encoder untuk data kategorikal, dengan fungsi pd.get_dummies
df = pd.get_dummies(df, columns=['Gender', 'Geography', 'HasCrCard', 'IsActiveMember'])

In [ ]:
# TODO: Pisahkan fitur (X) dengan target (Y), dimana Y merujuk ke kolom "Exited"
X = df.drop('Exited', axis=1)
y = df['Exited']

In [ ]:
scaler = MinMaxScaler() # TODO: Lakukan scaling atau normalisasi
X_transform = scaler.fit_transform(X)

In [ ]:
# Bagian ini digunakan jika Anda melakukan scaling atau normalisasi.
# Jika tidak, code ini bisa dilewati dan diganti dengan code yang ada di dalam comment.

X_transform = pd.DataFrame(X_transform, columns = X.columns)
# X_transform = X.copy()

### Train-Test Split

In [ ]:
X_train ,X_test, y_train, y_test = tts(X_transform, y, test_size = 0.25, random_state = 123)
display(df)

Age  Tenure    Balance  NumOfProducts  EstimatedSalary  Exited  \
0      42       2       0.00              1        101348.88       1   
1      41       1   83807.86              1        112542.58       0   
2      42       8  159660.80              3        113931.57       1   
3      39       1       0.00              2         93826.63       0   
4      43       2  125510.82              1         79084.10       0   
...   ...     ...        ...            ...              ...     ...   
9995   39       5       0.00              2         96270.64       0   
9996   35      10   57369.61              1        101699.77       0   
9997   36       7       0.00              1         42085.58       1   
9998   42       3   75075.31              2         92888.52       1   
9999   28       4  130142.79              1         38190.78       0   

      Gender_Female  Gender_Male  Geography_France  Geography_Germany  \
0              True        False              True              False   
1              True        False             False              False   
2              True        False              True              False   
3              True        False              True              False   
4              True        False             False              False   
...             ...          ...               ...                ...   
9995          False         True              True              False   
9996          False         True              True              False   
9997           True        False              True              False   
9998          False         True             False               True   
9999           True        False              True              False   

      Geography_Spain  HasCrCard_0  HasCrCard_1  IsActiveMember_0  \
0               False        False         True             False   
1                True         True        False             False   
2               False        False         True              True   
3               False         True        False              True   
4                True        False         True             False   
...               ...          ...          ...               ...   
9995            False        False         True              True   
9996            False        False         True             False   
9997            False         True        False             False   
9998            False        False         True              True   
9999            False        False         True              True   

      IsActiveMember_1  
0                 True  
1                 True  
2                False  
3                False  
4                 True  
...                ...  
9995             False  
9996              True  
9997              True  
9998             False  
9999             False  

[10000 rows x 15 columns]

### Model #1

In [ ]:
# [ PERTANYAAN ]
# TODO: Jelaskan secara singkat model #1 yang Anda gunakan.
"""
Model yang kami digunakan dalam model 1 ini adalah Random Forest.
Random Forest adalah algoritma ensemble yang menggabungkan beberapa pohon keputusan untuk meningkatkan akurasi dan mengurangi risiko overfitting.
Ini adalah salah satu teknik yang paling umum digunakan dalam machine learning karena kemampuannya untuk menangani data yang kompleks dan beragam.
Kami mencoba model tersebut d   engan run time sekitar 15 menit dengan tingkat akurasi 86.2%
"""

'\nModel yang kami digunakan dalam model 1 ini adalah Random Forest.\nRandom Forest adalah algoritma ensemble yang menggabungkan beberapa pohon keputusan untuk meningkatkan akurasi dan mengurangi risiko overfitting. \nIni adalah salah satu teknik yang paling umum digunakan dalam machine learning karena kemampuannya untuk menangani data yang kompleks dan beragam.\nKami mencoba model tersebut dengan run time sekitar 15 menit dengan tingkat akurasi 86.2%\n'

[ ANSWER HERE ]

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# TODO: Pilih salah satu model Machine Learning (ML) dari Scikit-learn
model_rf = RandomForestClassifier()

params = {
    'n_estimators': [100, 200, 300],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': [None, 'sqrt', 'log2'],
}

# OPTIONAL: Lakukan hyperparameter tuning sesuai kebutuhan
grid = GridSearchCV(
    estimator=model_rf,
    param_grid=params,
    scoring='accuracy',
    n_jobs=10,
    cv=10
)

grid.fit(X_train, y_train)
best_params = grid.best_params_

In [ ]:
y_pred = grid.predict(X_test) # TODO: Lakukan evaluasi untuk model #1

print(classification_report(y_test, y_pred))
print("")
print(confusion_matrix(y_test, y_pred))
print("")
print(accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.96      0.92      1983
           1       0.76      0.49      0.60       517

    accuracy                           0.86      2500
   macro avg       0.82      0.73      0.76      2500
weighted avg       0.85      0.86      0.85      2500


[[1904   79]
 [ 263  254]]

0.8632


### Model #2

In [ ]:
# [ PERTANYAAN ]
# TODO: Jelaskan secara singkat model #2 yang Anda gunakan.
"""
Model yang kami gunakan pada model 2 ini adalah Support Vector Classifier (SVC).
Support Vector Classifier (SVC) adalah teknik machine learning yang bertujuan untuk menemukan
hyperplane optimal yang dapat memisahkan kelas-kelas dalam data dengan margin maksimal.
SVC dapat digunakan untuk masalah klasifikasi biner maupun multi-kelas.
Model ini terkenal karena kemampuannya dalam bekerja dengan data yang tidak terpisah secara linear melalui penggunaan kernel trick.
Kami mencoba model tersebut dengan run time sekitar 10 menit dengan tingkat akurasi 86.4%
"""

'\nModel yang kami gunakan pada model 2 ini adalah Support Vector Classifier (SVC).\nSupport Vector Classifier (SVC) adalah teknik machine learning yang bertujuan untuk menemukan \nhyperplane optimal yang dapat memisahkan kelas-kelas dalam data dengan margin maksimal. \nSVC dapat digunakan untuk masalah klasifikasi biner maupun multi-kelas. \nModel ini terkenal karena kemampuannya dalam bekerja dengan data yang tidak terpisah secara linear melalui penggunaan kernel trick.\nKami mencoba model tersebut dengan run time sekitar 10 menit dengan tingkat akurasi 86.4%\n'

[ ANSWER HERE ]

In [ ]:
import numpy as np
import pandas as pd
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score


# TODO: Pilih salah satu model Machine Learning (ML) dari Scikit-learn
model2 = SVC()
params = {
    'C': [0.1, 1, 10, 100],
    'kernel': ['linear', 'rbf', 'poly'],
    'gamma': ['scale', 'auto']
}

# OPTIONAL: Lakukan hyperparameter tuning sesuai kebutuhan
grid = GridSearchCV(
    estimator=model2,
    param_grid=params,
    scoring='accuracy',
    n_jobs=10,
    cv=10
)

grid.fit(X_train, y_train)
best_params = grid.best_params_

In [ ]:
y_pred = grid.predict(X_test)  # TODO: Lakukan evaluasi untuk model #2

print(classification_report(y_test, y_pred))
print("")
print(confusion_matrix(y_test, y_pred))
print("")
print(accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.87      0.98      0.92      1983
           1       0.82      0.44      0.57       517

    accuracy                           0.86      2500
   macro avg       0.85      0.71      0.74      2500
weighted avg       0.86      0.86      0.85      2500


[[1935   48]
 [ 292  225]]

0.864


### Model #3

In [ ]:
# [ PERTANYAAN ]
# TODO: Jelaskan secara singkat model #3 yang Anda gunakan.
"""
Model yang kami gunakan pada model 3 ini adalah GradientBoostingClassifier.
Kode di atas menggunakan Gradient Boosting Classifier untuk melakukan klasifikasi.
Model ini merupakan metode ensemble yang membangun sejumlah pohon keputusan secara bertahap,
di mana setiap pohon baru memperbaiki kesalahan dari pohon sebelumnya.
Kami mencoba model tersebut dengan run time sekitar 3 menit dengan tingkat akurasi 86.64%
"""

'\nModel yang kami gunakan pada model 3 ini adalah GradientBoostingClassifier.\nKode di atas menggunakan Gradient Boosting Classifier untuk melakukan klasifikasi.\nModel ini merupakan metode ensemble yang membangun sejumlah pohon keputusan secara bertahap,\ndi mana setiap pohon baru memperbaiki kesalahan dari pohon sebelumnya.\nKami mencoba model tersebut dengan run time sekitar 3 menit dengan tingkat akurasi 86.64%\n'

[ ANSWER HERE ]

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import GridSearchCV

# TODO: Pilih salah satu model Machine Learning (ML) dari Scikit-learn
model3 = GradientBoostingClassifier()

params = {
    "n_estimators": [100, 200],
    "learning_rate": [0.01, 0.1],
    "max_depth": [3, 5],
    "min_samples_split": [2, 5],
    "min_samples_leaf": [1, 2]
}

# OPTIONAL: Lakukan hyperparameter tuning sesuai kebutuhan
grid = GridSearchCV(
    estimator=model3,
    param_grid=params,
    scoring='accuracy',
    n_jobs=10,
    cv=10
)

grid.fit(X_train, y_train)
best_params = grid.best_params_


In [ ]:
y_pred = grid.predict(X_test)  # TODO: Lakukan evaluasi untuk model #3

print(classification_report(y_test, y_pred))
print("")
print(confusion_matrix(y_test, y_pred))
print("")
print(accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.96      0.92      1983
           1       0.76      0.51      0.61       517

    accuracy                           0.87      2500
   macro avg       0.82      0.74      0.77      2500
weighted avg       0.86      0.87      0.86      2500


[[1901   82]
 [ 252  265]]

0.8664


### Conclusion

In [ ]:
# [ PERTANYAAN ]
# TODO: Tarik kesimpulan model mana yang terbaik beserta alasannya

"""
Gradient Boosting Classifier dapat mengatasi masalah yang kompleks dengan membangun beberapa pohon keputusan yang memperbaiki kesalahan dari model sebelumnya,
sehingga model ini cenderung lebih baik dalam menangani variabilitas dalam data. Meskipun waktu komputasinya lebih singkat
(sekitar 3 menit) dibandingkan Random Forest (15 menit) dan SVC (10 menit), Gradient Boosting tetap memberikan performa yang lebih tinggi,
menjadikannya pilihan terbaik dalam tugas klasifikasi ini.
"""

[ ANSWER HERE ]

### Scoring
Total `#TODO` = 13
<br>Checklist:

- [ ] Hilangkan kolom yang tidak relevan untuk pemodelan
- [ ] Lakukan One-Hot Encoder untuk data kategorikal, dengan fungsi pd.get_dummies
- [ ] Pisahkan fitur (X) dengan target (Y), dimana Y merujuk ke kolom "Exited"
- [ ] Lakukan scaling atau normalisasi
- [ ] Jelaskan secara singkat model #1 yang Anda gunakan
- [ ] Pilih salah satu model Machine Learning (ML) dari Scikit-learn (model #1)
- [ ] Lakukan evaluasi untuk model #1
- [ ] Jelaskan secara singkat model #2 yang Anda gunakan
- [ ] Pilih salah satu model Machine Learning (ML) dari Scikit-learn (model #2)
- [ ] Lakukan evaluasi untuk model #2
- [ ] Jelaskan secara singkat model #3 yang Anda gunakan
- [ ] Pilih salah satu model Machine Learning (ML) dari Scikit-learn (model #3)
- [ ] Lakukan evaluasi untuk model #3

### Additional readings
- N/A

### Copyright © 2024 Startup Campus, Indonesia
* You may **NOT** use this file except there is written permission from PT. Kampus Merdeka Belajar (Startup Campus).
* Please address your questions to mentors.